### ISSUE TITLE
xarray_to_video and coastlines

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#100]
Related to #97, probably worth tackling as one. Worth offering non contour options for landmasks too.

**Comment by JimCircadian** [comment]
Cartopy and FuncAnimation don't yet appear to operate well together, so placing a hold on investigating this for the driving force of the functionality, but have added `ax_init` and `ax_extra` arguments that help in allowing this to happen.

**Comment by JimCircadian** [comment]
@tom-andersson mentioned [this alternative](https://pypi.org/project/celluloid/) to the matplotlib native animation library for producing videos. Might be worth a look (perhaps as an optional dependency?)

**Comment by JimCircadian** [comment]
A quick look suggests that it's directly integrated with matplotlib, so testing alongside cartopy will be prudent

**Comment by ots22** [comment]
I was playing around with FuncAnimation with cartopy and have something working in a notebook. I could try to get this into xarray_to_video, but is this still worth pursuing given the above?

**Comment by ots22** [comment]
I'm not completely sure yet! I suspect it might need some changes to xarray_to_video but I'll try to avoid breaking the existing interface.
