### ISSUE TITLE
Command for local SIC error plots

### ISSUE THREAD

**Issue by ots22** [icenet-ai/icenet#104]
IceNet version: 0.2.1

### Description

A command that produces data for line plots of SIC and error from a forecast and corresponding observations, at specified 'probe' locations.

Proposed interface:

```
icenet_plot_sic_error_local <hemisphere> <forecast-name> <forecast-date> \
    --probe <probe1-name> <probe1-location>
    --probe <probe2-name> <probe2-location>
    ...
    -o output.csv
    --make-figure output.png
    [--figure-opts ...]
```

**Comment by JimCircadian** [comment]
Worth noting that there's a `region_arg` method I use for the existing bin accuracy and sic error video commands, so worth picking up on that if possible 😉

**Comment by JimCircadian** [comment]
@ots22 I'm looking to produce the 0.2.2 release. Would you be able to confirm if these will be good to go into that release?

**Comment by ots22** [comment]
Hi @JimCircadian, yes it would be great if we could include this - some things left to do (see the PR) but should be ready early next week if that fits with your timeline?

**Comment by JimCircadian** [comment]
No problem @ots22, happy to wait for it to be finished! Just after getting 0.2.2 out prior to my hols 🏄🏼
