### ISSUE TITLE
Fix error when using `train_model` without passing in `callback_objects`

### ISSUE THREAD

**Issue by rchan26** [icenet-ai/icenet#170]
The default for `callback_objects` in `train_model` is currently `[None](https://github.com/icenet-ai/icenet/blob/main/icenet/model/train.py#L31)`, but this will raise an error as there's an attempt to concatenate a list with None.

Fix by making the default an empty list.

**Comment by JimCircadian** [comment]
Fixed in @rchan26 so have unassigned while I evaluate what's left in 0.2.6 to fix 😉
