### ISSUE TITLE
Python 3.7 install: older Cartopy requires dependencies installed firsthand

### ISSUE THREAD

**Issue by bnubald** [icenet-ai/icenet#196]
* IceNet version: v0.3.0_dev
* Python version: 3.7
* Operating System: Windows (WSL2 Ubuntu 22.04.3 LTS)

### Description

Installing from source (and also via pypi) in Python 3.7 results in install error.

### What I Did

1. Empty Python 3.7 virtual environment set up with virtualenv.
```bash
$ pip list
Package    Version
---------- -------
Cython     3.0.5
pip        23.3.1
setuptools 68.0.0
wheel      0.41.3
```

2. Installing both from source, and via pip install results in following error (in blank environment).

```bash
$ pip install -e
  ...
  Using cached Cartopy-0.18.0.tar.gz (14.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-install-t9r5pqao/cartopy_48cbfc70666d48e99578b26dfe4e4ffc/setup.py", line 43, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-t9r5pqao/cartopy_48cbfc70666d48e99578b26dfe4e4ffc/setup.py", line 45, in <module>
          raise ImportError('NumPy 1.10+ is required to install cartopy.')
      ImportError: NumPy 1.10+ is required to install cartopy.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Possible solution

Precede cartopy install with numpy. 

Might be prudent to drop 3.7 support since past EOL.

**Comment by davidwilby** [comment]
I've noticed a possibly related issue using python 3.8 in which pip installs of icenet (either pypi or local source) fail with the following error:

icenet version: 0.2.7

```
...
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cartopy
Failed to build cartopy
ERROR: Could not build wheels for cartopy, which is required to install pyproject.toml-based projects
```

I also replicate the above error with python 3.7 - would agree with dropping support.
Installs successfully for 3.11.

(out of interest, 3.12 installation fails due to not finding a compatible version of tensorflow)

**Comment by bnubald** [comment]
Hm.. interesting, hadn't come across the issue in 3.8.

Could it be because of [this](https://stackoverflow.com/questions/74762739/struggling-to-install-cartopy)?

I do recall having to install the geos library separately when trying to debug this in 3.7 (possibly a header dependency).

The current supported Python versions is between 3.8-3.11 (Latest supported by Tensorflow). 3.12 will be supported when tensorflow adds support for it.

The supported versions has been updated in the newer pyproject.toml in v0.3.0, but looks like not updated in setup.py yet, also relates to #197 .

https://github.com/icenet-ai/icenet/blob/cb1cb785808ba1138c0ed0f8f88208a144daa6ff/setup.py#L33-L37

**Comment by davidwilby** [comment]
Ah yeah, this would explain why I don't get the issue when following the pipeline setup, since cartopy is installed using conda there.

Interesting, though, that there isn't an issue for python>3.8

**Comment by davidwilby** [comment]
I would agree that it's now valid to drop python 3.7 support, is this already happening in 0.3.0? Maybe we should also elaborate on some of the dependency explanation in the readme?

**Comment by bnubald** [comment]
Solution for 3.8 is to install geos either at system level, or using conda before installing icenet since its looking for the geos header file, i.e.

```bash
$ conda install -c conda-forge geos
$ pip install icenet
```

Python 3.9+ does have this error.
