### ISSUE TITLE
Dask LocalCluster resource not closed upon completion

### ISSUE THREAD

**Issue by bnubald** [icenet-ai/icenet#231]
* IceNet version: v0.2.7, v0.2.8a1
* Python version: 3.11
* Operating System: Linux x64, BAS HPC

### Description

After generating a data loader (using `DaskBaseDataLoader`/`DaskMultiWorkerLoader`), workers are not stopped and memory is not released upon completion.

This has been an issue when attempting to run on Binder with limited memory.

### What I Did

The following is run in a cell in a jupyter notebook.

```python
from icenet.data.loaders import IceNetDataLoaderFactory

implementation = "dask"
loader_config = f"loader.{processed_name}.json"
dataset_name = "api_dataset"
lag = 1

dl = IceNetDataLoaderFactory().create_data_loader(
    implementation,
    loader_config,
    dataset_name,
    lag,
    n_forecast_days=3,
    north=False,
    south=True,
    output_batch_size=1,
    generate_workers=1
)

dl.generate()
```

The workers started are not stopped once the cell finishes running.

Relevant part of the code:

https://github.com/icenet-ai/icenet/blob/cb1cb785808ba1138c0ed0f8f88208a144daa6ff/icenet/data/loaders/dask.py#L69-L81

Solution:
Close cluster explicitly/wrap within context.

**Comment by JimCircadian** [comment]
This is to be expected, as the cluster remains active for the lifetime of the kernel unless explicitly destroyed. Be careful of side effects to changing this purely to work within notebook-style contexts! 👍🏼

**Comment by bnubald** [comment]
> This is to be expected, as the cluster remains active for the lifetime of the kernel unless explicitly destroyed. Be careful of side effects to changing this purely to work within notebook-style contexts! 👍🏼

Posted a PR before seeing comment 😓

**Comment by JimCircadian** [comment]
All good, I like it for the moment. Continue unhindered! :D
