### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by bnubald** [icenet-ai/icenet#273]
* IceNet version: 3.8

### Description

As per title.

@JimCircadian are we able to move away from Python 3.8 for operational forecasts? It's getting more and more tricky to keep support due to dependencies.

Would like to drop for v0.2.9 release.

I ask because of #229 and #230.

**Comment by JimCircadian** [comment]
Yes, go for it. I'm happy just stepping up to 3.9 to maximise compatibility with system level installations, but 3.8 is now reasonably far behind the curve so am up for this
