### ISSUE TITLE
Integrate requirements properly for independent install

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet#48]
Still relying on the icenet-pipeline requirements / conda setup for installation of the necessary requirements, but this needs to be stated/sorted within the icenet package itself. 

Backport these changes

**Comment by JimCircadian** [comment]
Using this to catch a minimal build for basic functionality that is useful for docker builds: get rid of extreme dependencies like tensorflow and cartopy by making them optional. Ensure this is reflected in the icenet README #156

**Comment by bnubald** [comment]
@JimCircadian Has this been covered via the requirements file in the latest releases?

**Comment by JimCircadian** [comment]
Yes, closing for the moment as icenet is successfully deployed in various situations without the conda environment being required
