### ISSUE TITLE
Wandb account required even when not attempting to visualize training

### ISSUE THREAD

**Issue by ots22** [icenet-ai/icenet#83]
* IceNet version: 0.2.0
* Python version: 3.8.13
* Operating System: CentOS Linux release 7.9.2009 (Core)

### Description

Running the training command from `icenet-notebooks/01.cli_demonstration.ipynb` requires a wandb account, even when selecting 'don't visualize my results'.

It's possible to pass the `-nw` (`--no-wandb`) flag to avoid this, but I'd probably still expect the 'don't visualise' option to work.

### What I Did

```
icenet_train notebook_data notebook_testrun 42 -b 2 -e 10 -m -qs 4 -w 4 -n 0.6                        
2023-02-01 18:05:03.804863: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neura
l Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[01-02-23 18:05:08 :WARNING ] - Setting seed for best attempt at determinism, value 42
[01-02-23 18:05:08 :INFO    ] - Loading configuration dataset_config.notebook_data.json
[01-02-23 18:05:08 :INFO    ] - Training dataset path: ./network_datasets/notebook_data/south/train
[01-02-23 18:05:08 :INFO    ] - Validation dataset path: ./network_datasets/notebook_data/south/val
[01-02-23 18:05:08 :INFO    ] - Test dataset path: ./network_datasets/notebook_data/south/test
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: ERROR Error while calling W&B API: user is not logged in (<Response [401]>)
```

**Comment by JimCircadian** [comment]
Thanks @ots22, this definitely isn't what we want. The issue will be with the `wandb.init` call not respecting that we're not uploading / linking to an account. It might be a change in behaviour, or native, that it automatically queries for an initialised wandb system. As things can be saved locally, perhaps there's an option in `wandb.init` that will prevent this check!

**Comment by JimCircadian** [comment]
@ots22 there is a `-wo` / `--wandb-offline` option, have you tried using that?

**Comment by ots22** [comment]
Thanks - I found `--no-wandb` fixed it for me and I didn't investigate further. What is the difference between `-nw` and `-wo`?

**Comment by JimCircadian** [comment]
`-wo` switches wandb to cache results locally, `-nw` just turns it off. The message you got was from the wandb library itself, so it might require the use of `-wo`. These options probably need clearing up a bit as one supersedes the other look at it. 😉
