### ISSUE TITLE
Validation 'summary' command

### ISSUE THREAD

**Issue by ots22** [icenet-ai/icenet#94]
Add a command that aggregates the output of several validation commands into a summary report

**Comment by JimCircadian** [comment]
@rchan26 this looks like a great issue for the AI UK presentation, fancy assigning to 0.2.4?

**Comment by rchan26** [comment]
Sure @JimCircadian - let's do it!

**Comment by JimCircadian** [comment]
@ots22 @rchan26 I think this is happily fixed by [the work in the pipeline linking together the plotting](https://github.com/icenet-ai/icenet-pipeline/pull/22). If you agree, happy to close?

**Comment by rchan26** [comment]
Sorry @JimCircadian. I missed this message, but yes, I think this is done. Closing this.
