### ISSUE TITLE
Missing plot_sample

### ISSUE THREAD

**Issue by ots22** [icenet-ai/icenet#98]
* IceNet version: 0.2.0
* Python version:
* Operating System:

### Description

The icenet_plot_sample entry point in setup.py is set to a nonexistent function `icenet.plotting.data:plot_sample` (which doesn't seem to appear at any revision).

### What I Did

```
$ icenet_plot_sample
...
AttributeError: module 'icenet.plotting.data' has no attribute 'plot_sample'
```

**Comment by JimCircadian** [comment]
Oops! This was intended as a method to load data from a data loader file (e.g. after preprocessing, as opposed to a tfrecord, using a `loader.nom.json` configuration). Interestingly, that overlaps with the functionality `icenet_video_data` provides (it allows you to produce video files for the very same data.) This is all a bit old and stale but useful utilities to have, so worth rectifying or removing. 

Definitely need to get some testing around this to ensure all entry points are working! 😄 Great catch, thank you.

**Comment by JimCircadian** [comment]
`icenet_plot_sample` has been removed
